package net.mads.industron.material.generation;

import net.mads.industron.material.ElementDefinition;
import net.mads.industron.material.IndustrialMaterial;
import net.mads.industron.material.MaterialCatalog;
import net.mads.industron.material.MaterialCategory;
import net.mads.industron.material.defenitions.CompoundMaterials;
import net.mads.industron.material.defenitions.IndustrialMaterials;

import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Keeps the compile-time {@code Metal.X} namespace synchronized with the real material system.
 *
 * <p>The source of truth remains {@link IndustrialMaterials} and {@link CompoundMaterials}.
 * This generator only emits aliases for entries whose calculated {@link MaterialCategory} is
 * {@link MaterialCategory#METAL}. It is run from the data-generation bootstrap after the complete
 * material registry has been initialized.</p>
 *
 * <p>Because Java field names must exist at compile time, the generated source is committed in the
 * source tree. Adding a brand-new metal definition and running {@code runData} once adds the new
 * {@code Metal.NAME} alias automatically for subsequent compilation.</p>
 */
public final class MetalAliasSourceGenerator {
    private static final String GENERATED_RELATIVE_PATH =
            "net/mads/industron/material/generated/Metal.java";

    private MetalAliasSourceGenerator() {
    }

    public static void sync() {
        Path sourceRoot = findJavaSourceRoot();
        if (sourceRoot == null) {
            System.err.println("[Industron Materials] Could not locate src/main/java; Metal aliases were not synchronized.");
            return;
        }

        Path target = sourceRoot.resolve(GENERATED_RELATIVE_PATH);
        String source = render();
        try {
            Files.createDirectories(target.getParent());
            if (Files.exists(target)) {
                String current = Files.readString(target, StandardCharsets.UTF_8);
                if (current.equals(source)) return;
            }
            Files.writeString(target, source, StandardCharsets.UTF_8);
            System.out.println("[Industron Materials] Synchronized generated metal aliases: "
                    + target.toAbsolutePath());
        } catch (IOException e) {
            throw new IllegalStateException("Failed to synchronize generated Metal.java at " + target, e);
        }
    }

    static String render() {
        List<Alias> elementAliases = collectElementAliases();
        List<Alias> compoundAliases = collectCompoundAliases();

        StringBuilder out = new StringBuilder(16_384);
        out.append("package net.mads.industron.material.generated;\n\n")
                .append("import net.mads.industron.material.ElementDefinition;\n")
                .append("import net.mads.industron.material.IndustrialMaterial;\n")
                .append("import net.mads.industron.material.MaterialCatalog;\n")
                .append("import net.mads.industron.material.MaterialCategory;\n")
                .append("import net.mads.industron.material.defenitions.CompoundMaterials;\n")
                .append("import net.mads.industron.material.defenitions.IndustrialMaterials;\n\n")
                .append("import java.util.List;\n\n")
                .append("/**\n")
                .append(" * AUTO-GENERATED by MetalAliasSourceGenerator. DO NOT EDIT BY HAND.\n")
                .append(" * Real definitions remain in IndustrialMaterials / CompoundMaterials.\n")
                .append(" */\n")
                .append("public final class Metal {\n");

        if (!elementAliases.isEmpty()) {
            out.append("    // Elemental metals.\n");
            for (Alias alias : elementAliases) {
                out.append("    public static final ElementDefinition ")
                        .append(alias.name())
                        .append(" = IndustrialMaterials.")
                        .append(alias.name())
                        .append(";\n");
            }
            out.append('\n');
        }

        if (!compoundAliases.isEmpty()) {
            out.append("    // Metallic alloys / compounds.\n");
            for (Alias alias : compoundAliases) {
                out.append("    public static final IndustrialMaterial ")
                        .append(alias.name())
                        .append(" = CompoundMaterials.")
                        .append(alias.name())
                        .append(";\n");
            }
            out.append('\n');
        }

        out.append("    /** All currently registered materials whose calculated category is METAL. */\n")
                .append("    public static final List<IndustrialMaterial> ALL = MaterialCatalog.all(MaterialCategory.METAL);\n\n")
                .append("    private Metal() {\n")
                .append("    }\n")
                .append("}\n");
        return out.toString();
    }

    private static List<Alias> collectElementAliases() {
        List<Alias> aliases = new ArrayList<>();
        for (Field field : IndustrialMaterials.class.getDeclaredFields()) {
            if (!Modifier.isPublic(field.getModifiers())
                    || !Modifier.isStatic(field.getModifiers())
                    || field.getType() != ElementDefinition.class) {
                continue;
            }
            try {
                ElementDefinition definition = (ElementDefinition) field.get(null);
                IndustrialMaterial material = definition == null ? null : MaterialCatalog.find(definition.id());
                if (material != null && MaterialCategory.METAL.matches(material)) {
                    aliases.add(new Alias(field.getName()));
                }
            } catch (IllegalAccessException e) {
                throw new IllegalStateException("Could not inspect element alias " + field.getName(), e);
            }
        }
        aliases.sort(Comparator.comparing(Alias::name));
        return List.copyOf(aliases);
    }

    private static List<Alias> collectCompoundAliases() {
        List<Alias> aliases = new ArrayList<>();
        for (Field field : CompoundMaterials.class.getDeclaredFields()) {
            if (!Modifier.isPublic(field.getModifiers())
                    || !Modifier.isStatic(field.getModifiers())
                    || field.getType() != IndustrialMaterial.class) {
                continue;
            }
            try {
                IndustrialMaterial material = (IndustrialMaterial) field.get(null);
                if (material != null && MaterialCategory.METAL.matches(material)) {
                    aliases.add(new Alias(field.getName()));
                }
            } catch (IllegalAccessException e) {
                throw new IllegalStateException("Could not inspect compound metal alias " + field.getName(), e);
            }
        }
        aliases.sort(Comparator.comparing(Alias::name));
        return List.copyOf(aliases);
    }

    private static Path findJavaSourceRoot() {
        Path cursor = Path.of("").toAbsolutePath().normalize();
        for (int depth = 0; depth < 8 && cursor != null; depth++) {
            Path candidate = cursor.resolve("src").resolve("main").resolve("java");
            if (Files.isDirectory(candidate)) return candidate;
            cursor = cursor.getParent();
        }
        return null;
    }

    private record Alias(String name) {
    }
}
