package net.mads.industron.material.chemistry.integration;

import net.mads.industron.fluid.IndustrialFluidLookup;
import net.mads.industron.machine.MachineTier;
import net.mads.industron.material.IndustrialMaterial;
import net.mads.industron.material.MaterialPart;
import net.mads.industron.material.structure.StructureMaterial;
import net.mads.industron.material.structure.StructureMaterialGenerator;
import net.mads.industron.Industron;
import net.mads.industron.material.chemistry.ChemistryDiagnostic;
import net.mads.industron.material.chemistry.ChemistryPhase;
import net.mads.industron.material.chemistry.ChemistryStatus;
import net.mads.industron.material.chemistry.MaterialAnalysis;
import net.mads.industron.material.chemistry.process.CompatibleMaterialResolver;
import net.mads.industron.material.chemistry.process.ProcessIntent;
import net.mads.industron.material.chemistry.process.ProcessMaterial;
import net.mads.industron.material.chemistry.process.ProcessRecipeResolver;
import net.mads.industron.material.chemistry.process.ProcessRecipeNormalizer;
import net.mads.industron.material.chemistry.process.ProcessSubstanceState;
import net.mads.industron.material.chemistry.process.ProcessPlan;
import net.mads.industron.material.chemistry.process.ProcessRequirement;
import net.mads.industron.material.chemistry.process.ProcessSemantics;
import net.mads.industron.material.chemistry.process.ProcessSafetyValidator;
import net.mads.industron.material.chemistry.process.ProcessStep;
import net.mads.industron.material.chemistry.process.PropertyConstraint;
import net.mads.industron.material.recipes.MaterialRecipeHelper;
import net.mads.industron.recipe.RecipeDefinition;
import net.mads.industron.recipe.RecipeTypeDefinition;
import net.minecraft.data.recipes.RecipeOutput;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * Emits chemistry plans through Industron's existing {@link RecipeDefinition} API.
 *
 * <p>The historical class name is kept so older integration references do not break; this implementation
 * no longer uses reflection and never creates a parallel recipe type.</p>
 */
public final class ReflectiveRecipeEmitter {
    private static final List<MaterialPart> SOLID_PART_PREFERENCE = List.of(
            MaterialPart.DUST,
            MaterialPart.BIOLOGICAL_FEED,
            MaterialPart.GEM,
            MaterialPart.ROUGH_GEM,
            MaterialPart.INGOT,
            MaterialPart.RAW_ORE,
            MaterialPart.CRUSHED_ORE,
            MaterialPart.BLOCK,
            MaterialPart.PLATE
    );

    public record Result(
            int emitted,
            Set<String> emittedPlanIds,
            List<ChemistryDiagnostic> diagnostics
    ) {
        public Result {
            emittedPlanIds = Set.copyOf(emittedPlanIds == null ? Set.of() : emittedPlanIds);
            diagnostics = List.copyOf(diagnostics);
        }
    }

    private final CompatibleMaterialResolver resolver = new CompatibleMaterialResolver();
    private final ProcessRecipeResolver processResolver = new ProcessRecipeResolver();

    public Result emit(RecipeOutput output, List<ProcessPlan> plans, Map<String, MaterialAnalysis> materials) {
        List<ChemistryDiagnostic> diagnostics = new ArrayList<>();
        Set<String> emittedPlanIds = new HashSet<>();

        // Phase 1: preflight every candidate plan without touching RecipeOutput. Atomicity must span
        // the complete autogenerated graph, not merely the steps inside one plan: an upstream split
        // must never be written before we know that every required downstream DUST plan can also be
        // represented by the existing recipe system.
        List<PreparedPlan> preflightPassed = new ArrayList<>();
        for (ProcessPlan plan : plans) {
            List<ChemistryDiagnostic> planDiagnostics = new ArrayList<>();
            List<PreparedRecipe> prepared = new ArrayList<>();
            Set<String> planIds = new HashSet<>();
            boolean validPlan = true;

            for (ProcessStep plannedStep : plan.steps()) {
                try {
                    ProcessStep step = ProcessRecipeNormalizer.reduceCommonBatch(plannedStep);
                    step.requireBalanced();
                    java.util.Optional<String> semanticProblem = ProcessSemantics.validate(step);
                    if (semanticProblem.isPresent()) {
                        planDiagnostics.add(emissionProblem(step,
                                "Invalid process phases: " + semanticProblem.orElseThrow() + "."));
                        validPlan = false;
                        break;
                    }

                    List<RequirementVariant> variants = variantsFor(plan, step, materials, planDiagnostics);
                    if (variants.isEmpty()) {
                        validPlan = false;
                        break;
                    }

                    for (RequirementVariant variant : variants) {
                        String recipeId = variantRecipeId(step, variant, variants.size());
                        ProcessRecipeResolver.Result resolution = processResolver.resolveExact(step.kind(), ProcessIntent.fromStep(step));
                        if (resolution.resolution().isEmpty()) {
                            planDiagnostics.add(emissionProblem(step, resolution.diagnostic()));
                            validPlan = false;
                            break;
                        }
                        String fullKey = resolution.resolution().orElseThrow().recipeType().id() + "/" + recipeId;
                        // Cross-plan collisions are resolved only after every plan has passed its own
                        // preflight. Otherwise a plan that later fails could reserve an id and make
                        // another otherwise-valid plan fail simply because of iteration order.
                        if (!planIds.add(fullKey)) {
                            planDiagnostics.add(emissionProblem(step,
                                    "Duplicate generated recipe id " + fullKey + " inside one plan; atomic plan emission was cancelled."));
                            validPlan = false;
                            break;
                        }

                        ChemistryDiagnostic problem = validateEmission(step, variant, materials);
                        if (problem != null) {
                            planDiagnostics.add(problem);
                            validPlan = false;
                            break;
                        }
                        prepared.add(new PreparedRecipe(step, recipeId, variant, fullKey));
                    }
                    if (!validPlan) break;
                } catch (RuntimeException error) {
                    planDiagnostics.add(skip(plan, plannedStep,
                            error.getClass().getSimpleName() + ": " + safeMessage(error)));
                    validPlan = false;
                    break;
                }
            }

            diagnostics.addAll(planDiagnostics);
            if (!validPlan || prepared.isEmpty() && !plan.steps().isEmpty()) {
                diagnostics.add(planBlocked(plan));
                continue;
            }
            preflightPassed.add(new PreparedPlan(plan, prepared));
        }

        // Cross-plan recipe ids must be deterministic and unique. If two complete plans claim the
        // same id, block both instead of allowing list order to choose a winner. The downstream pass
        // below will then prune any parents that depended on either blocked plan.
        Map<String, List<PreparedPlan>> ownersByRecipe = new LinkedHashMap<>();
        for (PreparedPlan preparedPlan : preflightPassed) {
            for (PreparedRecipe recipe : preparedPlan.recipes()) {
                ownersByRecipe.computeIfAbsent(recipe.fullKey(), ignored -> new ArrayList<>()).add(preparedPlan);
            }
        }
        Set<String> duplicatePlanIds = new HashSet<>();
        for (Map.Entry<String, List<PreparedPlan>> entry : ownersByRecipe.entrySet()) {
            if (entry.getValue().size() <= 1) continue;
            for (PreparedPlan owner : entry.getValue()) {
                duplicatePlanIds.add(owner.plan().id());
                diagnostics.add(duplicateRecipeId(owner.plan(), entry.getKey()));
            }
        }
        if (!duplicatePlanIds.isEmpty()) {
            for (PreparedPlan preparedPlan : preflightPassed) {
                if (duplicatePlanIds.contains(preparedPlan.plan().id())) {
                    diagnostics.add(planBlocked(preparedPlan.plan()));
                }
            }
            preflightPassed.removeIf(preparedPlan -> duplicatePlanIds.contains(preparedPlan.plan().id()));
        }

        // Phase 2: emitter-specific failures can invalidate a downstream compound-DUST route even
        // though the planner/safety pass accepted it earlier. Re-run graph reachability over exactly
        // the plans that can really be serialized before writing anything.
        List<ProcessPlan> preflightPlans = preflightPassed.stream()
                .map(PreparedPlan::plan)
                .toList();
        ProcessSafetyValidator.Result reachable = new ProcessSafetyValidator()
                .validateCompleteChains(preflightPlans, materials);
        diagnostics.addAll(reachable.diagnostics());
        Set<String> reachablePlanIds = reachable.plans().stream()
                .map(ProcessPlan::id)
                .collect(java.util.stream.Collectors.toSet());

        // Phase 3: only now may RecipeOutput be mutated. A save failure still aborts the whole
        // datagen run because RecipeOutput has no rollback API; a failed run is never publishable.
        int emitted = 0;
        for (PreparedPlan preparedPlan : preflightPassed) {
            ProcessPlan plan = preparedPlan.plan();
            if (!reachablePlanIds.contains(plan.id())) continue;
            try {
                for (PreparedRecipe recipe : preparedPlan.recipes()) {
                    emitOne(output, recipe.step(), recipe.recipeId(), recipe.variant());
                    emitted++;
                }
                emittedPlanIds.add(plan.id());
            } catch (RuntimeException error) {
                throw new IllegalStateException(
                        "Atomic chemistry graph save failed for " + plan.id()
                                + " after global preflight; datagen is aborted to prevent accepting a partial chain.",
                        error
                );
            }
        }
        return new Result(emitted, emittedPlanIds, diagnostics);
    }

    private List<RequirementVariant> variantsFor(
            ProcessPlan plan,
            ProcessStep step,
            Map<String, MaterialAnalysis> materials,
            List<ChemistryDiagnostic> diagnostics
    ) {
        List<ProcessRequirement> concreteRequirements = step.requirements().stream()
                .filter(requirement -> requirement.role() != ProcessRequirement.Role.CHEMICAL_BALANCE)
                .toList();

        for (ProcessRequirement requirement : concreteRequirements) {
            if (requirement.consumed()) {
                diagnostics.add(new ChemistryDiagnostic(
                        ChemistryStatus.CHANGE_REQUIRED,
                        plan.targetMaterialId(),
                        "CONSUMED_REQUIREMENT_NOT_BALANCED",
                        "Property-selected consumed requirement " + requirement.role()
                                + " cannot be added unless its material also appears in the balanced outputs/recovery stream.",
                        List.of("Model consumed reagents as explicit ProcessMaterial inputs and include every consumed unit in guaranteed outputs/recovery."),
                        ""
                ));
                return List.of();
            }
        }

        // Process aids are deterministic too. A recipe must not fan out into many alternatives just
        // because several registered materials happen to satisfy the same property range. The same
        // target/composition therefore resolves the same best concrete catalyst/activator/etc. on
        // every run; fixed requirements naturally resolve to their single named material.
        Map<ProcessRequirement, MaterialAnalysis> resolved = new LinkedHashMap<>();
        for (ProcessRequirement requirement : concreteRequirements) {
            MaterialAnalysis candidate = resolver.resolveBest(requirement, materials).orElse(null);
            if (candidate == null) {
                diagnostics.add(new ChemistryDiagnostic(
                        ChemistryStatus.MISSING_MATERIAL,
                        plan.targetMaterialId(),
                        "NO_COMPATIBLE_" + requirement.role(),
                        "No registered material satisfies " + describe(requirement) + ".",
                        List.of("Create a fictional material whose calculated properties satisfy the requirement, then rerun runData."),
                        suggestedRequirementMaterial(requirement)
                ));
                return List.of();
            }
            resolved.put(requirement, candidate);
        }
        return List.of(new RequirementVariant(Map.copyOf(resolved)));
    }

    private ChemistryDiagnostic validateEmission(
            ProcessStep step,
            RequirementVariant variant,
            Map<String, MaterialAnalysis> materials
    ) {
        java.util.Optional<String> semanticProblem = ProcessSemantics.validate(step);
        if (semanticProblem.isPresent()) {
            return emissionProblem(step, "Invalid process phases: " + semanticProblem.orElseThrow() + ".");
        }

        ProcessRecipeResolver.Result resolution = processResolver.resolveExact(step.kind(), ProcessIntent.fromStep(step));
        if (resolution.resolution().isEmpty()) {
            return emissionProblem(step, resolution.diagnostic());
        }
        RecipeTypeDefinition type = resolution.resolution().orElseThrow().recipeType();
        if (type.requiresCoilTemperature() && step.requiredTemperature() <= 0) {
            return emissionProblem(step, "Coil-heated " + type.id() + " requires a positive temperature.");
        }

        int itemInputs = countSolid(step.inputs());
        int fluidInputs = countFluid(step.inputs());
        int itemOutputs = countSolid(step.outputs());
        int fluidOutputs = countFluid(step.outputs());

        for (Map.Entry<ProcessRequirement, MaterialAnalysis> entry : variant.materials().entrySet()) {
            ProcessRequirement requirement = entry.getKey();
            ChemistryPhase emittedPhase = requirement.requiredPhase() == ChemistryPhase.UNKNOWN
                    ? entry.getValue().phase()
                    : requirement.requiredPhase();
            if (emittedPhase.isFluidLike()) fluidInputs++;
            else itemInputs++;
        }

        if (itemInputs > type.maxItemInputs() || itemOutputs > type.maxItemOutputs()
                || fluidInputs > type.maxFluidInputs() || fluidOutputs > type.maxFluidOutputs()) {
            return emissionProblem(
                    step,
                    "Planned IO exceeds existing " + type.id() + " limits: items " + itemInputs + "->" + itemOutputs
                            + ", fluids " + fluidInputs + "->" + fluidOutputs + "; max "
                            + type.maxItemInputs() + "->" + type.maxItemOutputs() + ", "
                            + type.maxFluidInputs() + "->" + type.maxFluidOutputs() + "."
            );
        }

        for (ProcessMaterial material : concat(step.inputs(), step.outputs())) {
            ChemistryDiagnostic formProblem = validateMaterialForm(step, material);
            if (formProblem != null) return formProblem;
        }
        for (Map.Entry<ProcessRequirement, MaterialAnalysis> entry : variant.materials().entrySet()) {
            ProcessRequirement requirement = entry.getKey();
            MaterialAnalysis candidate = entry.getValue();
            ProcessMaterial material = new ProcessMaterial(
                    candidate.source().id(),
                    requirement.requiredPhase() == ChemistryPhase.UNKNOWN
                            ? candidate.phase()
                            : requirement.requiredPhase(),
                    Math.max(1, requirement.milliUnits()),
                    candidate.calculatedTierIndex(),
                    candidate.calculatedTierName(),
                    true,
                    candidate.source().backingMaterial(),
                    null,
                    ProcessSubstanceState.fromAnalysis(candidate),
                    candidate.properties().values()
            );
            ChemistryDiagnostic formProblem = validateMaterialForm(step, material);
            if (formProblem != null) return formProblem;
        }
        return null;
    }

    private static ChemistryDiagnostic validateMaterialForm(ProcessStep step, ProcessMaterial material) {
        Object backing = material.backingMaterial();
        if (!(backing instanceof IndustrialMaterial) && !(backing instanceof StructureMaterial)) {
            return emissionProblem(step, "Material " + material.materialId() + " has no supported definition backing object.");
        }
        if (resourceId(backing, material.phase(), material.part()) == null) {
            return emissionProblem(step, "Material " + material.materialId() + " has no registered form for phase " + material.phase() + ".");
        }
        try {
            if (material.phase().isFluidLike()) material.milliBucketsExact();
            else material.itemAmountExact();
        } catch (RuntimeException error) {
            return emissionProblem(step, "Material " + material.materialId()
                    + " has a non-serializable amount: " + safeMessage(error));
        }
        return null;
    }

    private void emitOne(
            RecipeOutput output,
            ProcessStep step,
            String recipeId,
            RequirementVariant variant
    ) {
        ProcessRecipeResolver.Result resolution = processResolver.resolveExact(step.kind(), ProcessIntent.fromStep(step));
        RecipeTypeDefinition type = resolution.resolution().orElseThrow(() ->
                new IllegalStateException(resolution.diagnostic())).recipeType();
        RecipeDefinition recipe = RecipeDefinition.recipe()
                .recipeDefinition(RecipeDefinition.Option.id(recipeId))
                .recipeDefinition(RecipeDefinition.Option.recipeType(type));

        for (ProcessMaterial input : step.inputs()) addMaterial(recipe, input, true, false);
        for (Map.Entry<ProcessRequirement, MaterialAnalysis> entry : variant.materials().entrySet()) {
            ProcessRequirement requirement = entry.getKey();
            MaterialAnalysis candidate = entry.getValue();
            ProcessMaterial material = new ProcessMaterial(
                    candidate.source().id(),
                    requirement.requiredPhase() == ChemistryPhase.UNKNOWN
                            ? candidate.phase()
                            : requirement.requiredPhase(),
                    Math.max(1, requirement.milliUnits()),
                    candidate.calculatedTierIndex(),
                    candidate.calculatedTierName(),
                    true,
                    candidate.source().backingMaterial(),
                    null,
                    ProcessSubstanceState.fromAnalysis(candidate),
                    candidate.properties().values()
            );
            addMaterial(recipe, material, true, !requirement.consumed());
        }

        for (ProcessRequirement requirement : step.requirements()) {
            if (requirement.role() == ProcessRequirement.Role.CHEMICAL_BALANCE) {
                PropertyConstraint balance = requirement.constraints().stream()
                        .filter(constraint -> constraint.property().equals("chemicalbalance"))
                        .findFirst()
                        .orElse(null);
                if (balance != null) {
                    double min = Math.max(-100, balance.minimum());
                    double max = Math.min(100, balance.maximum());
                    recipe.recipeDefinition(RecipeDefinition.Option.chemicalBalanceRange(min, max));
                }
            }
        }

        for (ProcessMaterial value : step.outputs()) addMaterial(recipe, value, false, false);
        recipe.recipeDefinition(RecipeDefinition.Option.duration(step.durationTicks()));
        recipe.recipeDefinition(RecipeDefinition.Option.tier(MachineTier.ALL.get(
                Math.min(step.recipeTierIndex(), MachineTier.ALL.size() - 1)
        )));
        if (type.requiresCoilTemperature()) {
            recipe.recipeDefinition(RecipeDefinition.Option.coilTemperature(step.requiredTemperature()));
        } else if (step.requiredTemperature() > 0) {
            recipe.recipeDefinition(RecipeDefinition.Option.temperature(step.requiredTemperature()));
        }
        recipe.save(output);
    }

    private static void addMaterial(RecipeDefinition recipe, ProcessMaterial value, boolean input, boolean notConsumed) {
        String resource = resourceId(value.backingMaterial(), value.phase(), value.part());
        if (value.phase().isFluidLike()) {
            int amount = value.milliBucketsExact();
            if (notConsumed) recipe.recipeDefinition(RecipeDefinition.Option.notConsumableFluid(resource, amount));
            else if (input) recipe.recipeDefinition(RecipeDefinition.Option.inputFluid(resource, amount));
            else recipe.recipeDefinition(RecipeDefinition.Option.outputFluid(resource, amount));
        } else {
            int amount = value.itemAmountExact();
            if (notConsumed) recipe.recipeDefinition(RecipeDefinition.Option.notConsumableItem(resource, amount));
            else if (input) recipe.recipeDefinition(RecipeDefinition.Option.inputItem(resource, amount));
            else recipe.recipeDefinition(RecipeDefinition.Option.outputItem(resource, amount));
        }
    }

    private static String resourceId(Object backing, ChemistryPhase phase, MaterialPart preferredPart) {
        if (backing instanceof IndustrialMaterial material) {
            return resourceId(material, phase, preferredPart);
        }
        if (!(backing instanceof StructureMaterial material) || phase.isFluidLike()) return null;
        MaterialPart part = preferredPart;
        if (part == null) {
            part = hasStructurePart(material, MaterialPart.DUST)
                    ? MaterialPart.DUST
                    : hasStructurePart(material, MaterialPart.WOOD_PULP)
                    ? MaterialPart.WOOD_PULP
                    : null;
        }
        if (part == null || !part.isItem() || !hasStructurePart(material, part)) return null;
        if (material.hasExistingPart(part)) return material.existingPart(part).toString();
        if (!StructureMaterialGenerator.generatedItemForms(material).contains(part)) return null;
        return Industron.MOD_ID + ":" + part.registryName(material);
    }

    private static boolean hasStructurePart(StructureMaterial material, MaterialPart part) {
        return material.hasExistingPart(part) || material.generatedForms().contains(part);
    }

    private static String resourceId(IndustrialMaterial material, ChemistryPhase phase, MaterialPart preferredPart) {
        if (preferredPart != null) {
            if (!material.has(preferredPart)) return null;
            if (preferredPart.isFluid()) {
                return IndustrialFluidLookup.fluidId(material, preferredPart).toString();
            }
            return MaterialRecipeHelper.itemId(material, preferredPart);
        }
        if (phase.isFluidLike()) {
            MaterialPart part = switch (phase) {
                case GAS, PLASMA -> MaterialPart.GAS;
                case MOLTEN -> MaterialPart.MOLTEN_FLUID;
                case LIQUID -> MaterialPart.LIQUID;
                default -> null;
            };
            if (part == null || !material.has(part)) return null;
            return IndustrialFluidLookup.fluidId(material, part).toString();
        }
        for (MaterialPart part : SOLID_PART_PREFERENCE) {
            if (material.has(part) && !part.isFluid()) return MaterialRecipeHelper.itemId(material, part);
        }
        return null;
    }

    private static String variantRecipeId(ProcessStep step, RequirementVariant variant, int totalVariants) {
        if (totalVariants <= 1 || variant.materials().isEmpty()) return step.id();
        StringBuilder id = new StringBuilder(step.id());
        variant.materials().entrySet().stream()
                .sorted(Map.Entry.comparingByKey(java.util.Comparator.comparing(value -> value.role().name())))
                .forEach(entry -> id.append("__")
                        .append(entry.getKey().role().name().toLowerCase(Locale.ROOT))
                        .append("_")
                        .append(entry.getValue().source().id()));
        return id.toString();
    }

    private static int countSolid(List<ProcessMaterial> materials) {
        return (int) materials.stream().filter(value -> !value.phase().isFluidLike()).count();
    }

    private static int countFluid(List<ProcessMaterial> materials) {
        return (int) materials.stream().filter(value -> value.phase().isFluidLike()).count();
    }

    private static List<ProcessMaterial> concat(List<ProcessMaterial> first, List<ProcessMaterial> second) {
        List<ProcessMaterial> values = new ArrayList<>(first.size() + second.size());
        values.addAll(first);
        values.addAll(second);
        return values;
    }

    private static ChemistryDiagnostic emissionProblem(ProcessStep step, String reason) {
        return new ChemistryDiagnostic(
                ChemistryStatus.OK_WITH_REQUIREMENTS,
                step.id(),
                "RECIPE_EMISSION_SKIPPED",
                reason,
                List.of("The process remains visible in build/reports/industron/chemistry/process-plans.txt.",
                        "Fix the material form/IO definition; do not create a new recipe type."),
                ""
        );
    }

    private static ChemistryDiagnostic skip(ProcessPlan plan, ProcessStep step, String reason) {
        return new ChemistryDiagnostic(
                ChemistryStatus.OK_WITH_REQUIREMENTS,
                plan.targetMaterialId(),
                "RECIPE_EMISSION_SKIPPED",
                "Could not emit " + step.id() + ": " + reason,
                List.of("The process plan remains in build/reports/industron/chemistry/process-plans.txt."),
                ""
        );
    }

    private static String describe(ProcessRequirement requirement) {
        return requirement.role() + " in phase " + requirement.requiredPhase() + " with " + requirement.constraints();
    }

    private static String suggestedRequirementMaterial(ProcessRequirement requirement) {
        return "// Required " + requirement.role() + "\n"
                + "public static final IndustrialMaterial CHANGE_ME = material(\"change_me\", \"Change Me\", 0x808080)\n"
                + "        .contains(/* component(...) */)\n"
                + "        // Must satisfy: " + requirement.constraints() + "\n"
                + "        .build();";
    }

    private static String safeMessage(Throwable error) {
        return error.getMessage() == null ? "<no message>" : error.getMessage();
    }

    private static ChemistryDiagnostic planBlocked(ProcessPlan plan) {
        return new ChemistryDiagnostic(
                ChemistryStatus.CHANGE_REQUIRED,
                plan.targetMaterialId(),
                "ATOMIC_PLAN_EMISSION_BLOCKED",
                "At least one step/variant in the generated chain failed preflight, so no recipe from this plan was emitted.",
                List.of("Fix the reported form, requirement, RecipeType or IO issue; rerun data generation to publish the complete chain atomically."),
                ""
        );
    }

    private static ChemistryDiagnostic duplicateRecipeId(ProcessPlan plan, String fullKey) {
        return new ChemistryDiagnostic(
                ChemistryStatus.CHANGE_REQUIRED,
                plan.targetMaterialId(),
                "DUPLICATE_GENERATED_RECIPE_ID",
                "Generated recipe id " + fullKey + " is claimed by more than one complete process plan; all colliding plans were blocked.",
                List.of("Make generated plan/step ids deterministic and unique, then rerun data generation; do not select a winner by iteration order."),
                ""
        );
    }

    private record PreparedPlan(
            ProcessPlan plan,
            List<PreparedRecipe> recipes
    ) {
        private PreparedPlan {
            recipes = List.copyOf(recipes);
        }
    }

    private record PreparedRecipe(
            ProcessStep step,
            String recipeId,
            RequirementVariant variant,
            String fullKey
    ) {
    }

    private record RequirementVariant(Map<ProcessRequirement, MaterialAnalysis> materials) {
        private RequirementVariant {
            materials = Map.copyOf(materials);
        }
    }
}
