package net.mads.industron.material.recipes;

import net.mads.industron.machine.MachineTier;
import net.mads.industron.machine.MachineTierStats;
import net.mads.industron.material.IndustrialMaterial;
import net.mads.industron.material.MaterialProperties;
import net.mads.industron.material.MaterialUnits;

import java.util.function.IntSupplier;

/** Shared deterministic progression/timing policy for autogenerated material processing. */
public final class MaterialProcessingRules {
    private static final int TICKS_PER_SECOND = 20;

    private MaterialProcessingRules() {
    }

    /** A material is normally processable one machine tier before the material itself is reached. */
    public static MachineTier processingTier(IndustrialMaterial material) {
        if (material == null) throw new IllegalArgumentException("Material cannot be null");
        return processingTier(material.tier());
    }

    /** Shared form for structure materials and other material families that expose only a tier. */
    public static MachineTier processingTier(MachineTier materialTier) {
        if (materialTier == null) throw new IllegalArgumentException("Material tier cannot be null");
        return MachineTierStats.offset(materialTier, -1);
    }

    /** Primitive material-production routes are intentionally limited to ULV and LV. */
    public static boolean allowsPrimitive(MachineTier tier) {
        return tier == MachineTier.ULV || tier == MachineTier.LV;
    }

    public static int crushingDuration(IndustrialMaterial material, int millibuckets) {
        MaterialProperties p = material.properties();
        double strength = nonNegative(p, "structuralStrength", p::structuralStrength, 25);
        double hardness = nonNegative(p, "hardness", p::hardness, Math.max(10.0D, strength * 0.60D));
        double fracture = nonNegative(p, "fractureToughness", p::fractureToughness, 25);
        double secondsPerUnit = 2.0D + hardness * 0.055D + strength * 0.018D + fracture * 0.012D;
        return amountScaledDuration(millibuckets, secondsPerUnit);
    }

    public static int pulverizingDuration(IndustrialMaterial material, int millibuckets) {
        MaterialProperties p = material.properties();
        double strength = nonNegative(p, "structuralStrength", p::structuralStrength, 25);
        double hardness = nonNegative(p, "hardness", p::hardness, Math.max(10.0D, strength * 0.60D));
        double brittleness = nonNegative(p, "brittleness", p::brittleness, 50);
        double secondsPerUnit = 3.0D + hardness * 0.045D + Math.max(0.0D, 50.0D - brittleness) * 0.020D;
        return amountScaledDuration(millibuckets, secondsPerUnit);
    }

    public static int washingDuration(IndustrialMaterial material, int millibuckets) {
        MaterialProperties p = material.properties();
        double density = nonNegative(p, "density", p::density, 50);
        double impurity = nonNegative(p, "impurityTolerance", p::impurityTolerance, 50);
        double secondsPerUnit = 5.0D + density * 0.020D + impurity * 0.025D;
        return amountScaledDuration(millibuckets, secondsPerUnit);
    }

    public static int compactingDuration(IndustrialMaterial material, int millibuckets) {
        MaterialProperties p = material.properties();
        double strength = nonNegative(p, "structuralStrength", p::structuralStrength, 25);
        double hardness = nonNegative(p, "hardness", p::hardness, strength * 0.60D);
        double secondsPerUnit = 2.5D + strength * 0.020D + hardness * 0.025D;
        return amountScaledDuration(millibuckets, secondsPerUnit);
    }

    /** Identity-preserving unpacking uses the same amount/material resistance scale as packing. */
    public static int decompactingDuration(IndustrialMaterial material, int millibuckets) {
        return compactingDuration(material, millibuckets);
    }

    public static int mixingDuration(IndustrialMaterial material, int materialUnits) {
        if (materialUnits <= 0) throw new IllegalArgumentException("Material units must be positive");
        MaterialProperties p = material.properties();
        double stability = nonNegative(p, "chemicalStability", p::chemicalStability, 50);
        double reactivity = nonNegative(p, "reactivity", p::reactivity, 50);
        double secondsPerUnit = 2.5D + stability * 0.018D + Math.max(0.0D, 50.0D - reactivity) * 0.012D;
        return amountScaledDuration(Math.multiplyExact(materialUnits, MaterialUnits.MILLIBUCKETS_PER_UNIT), secondsPerUnit);
    }

    public static int siftingDuration(IndustrialMaterial material, int millibuckets) {
        MaterialProperties p = material.properties();
        double density = nonNegative(p, "density", p::density, 50);
        double brittleness = nonNegative(p, "brittleness", p::brittleness, 50);
        double secondsPerUnit = 5.0D + density * 0.018D + brittleness * 0.018D;
        return amountScaledDuration(millibuckets, secondsPerUnit);
    }

    public static int meltingDuration(IndustrialMaterial material, int millibuckets) {
        MaterialProperties p = material.properties();
        double melting = nonNegative(p, "meltingPoint", p::meltingPoint, Math.max(0.0D, p.castTemperature()));
        double heatCapacity = nonNegative(p, "specificHeatCapacity", p::specificHeatCapacity, 50);
        double secondsPerUnit = 3.0D + melting * 0.0040D + heatCapacity * 0.012D;
        return amountScaledDuration(millibuckets, secondsPerUnit);
    }

    public static int centrifugingDuration(IndustrialMaterial material, int millibuckets, boolean purified) {
        MaterialProperties p = material.properties();
        double density = nonNegative(p, "density", p::density, 50);
        double stability = nonNegative(p, "chemicalStability", p::chemicalStability, 50);
        double base = purified ? 5.0D : 7.0D;
        double secondsPerUnit = base + density * 0.022D + stability * 0.018D;
        return amountScaledDuration(millibuckets, secondsPerUnit);
    }

    private static double nonNegative(
            MaterialProperties properties,
            String propertyName,
            IntSupplier getter,
            double fallback
    ) {
        if (!properties.hasProperty(propertyName)) return Math.max(0.0D, fallback);
        try {
            return Math.max(0.0D, getter.getAsInt());
        } catch (IllegalStateException unavailable) {
            return Math.max(0.0D, fallback);
        }
    }

    private static int amountScaledDuration(int millibuckets, double secondsPerUnit) {
        if (millibuckets <= 0) throw new IllegalArgumentException("Material amount must be positive");
        double units = millibuckets / (double) MaterialUnits.MILLIBUCKETS_PER_UNIT;
        long ticks = Math.round(Math.max(1.0D, secondsPerUnit * units) * TICKS_PER_SECOND);
        return (int) Math.max(1L, Math.min(Integer.MAX_VALUE, ticks));
    }
}
