package net.mads.industron.data;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import net.mads.industron.Industron;
import net.mads.industron.material.defenitions.PlantMaterials;
import net.mads.industron.material.plant.PlantMaterial;
import net.mads.industron.material.plant.PlantMaterialGenerator;
import net.mads.industron.material.plant.PlantPart;
import net.mads.industron.material.plant.PlantProcessingPlanner;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.CompletableFuture;

/**
 * Create integration for the same deterministic raw-plant preparation routes generated by
 * Industron. PlantPart chooses the physical process: cuttable structural forms use Mechanical Saw,
 * while seeds/roots/fruits/dried forms use Millstone.
 *
 * <p>Vanilla/Create-owned inputs are deliberately left to their existing Create recipes so this
 * provider never overwrites another mod's datapack ids. Industron/custom plant forms receive
 * Create adapters when the physical process matches.</p>
 */
public final class CreatePlantProcessingRecipeProvider implements DataProvider {
    private final Path dataPackRoot;

    public CreatePlantProcessingRecipeProvider(PackOutput output) {
        this.dataPackRoot = output.getOutputFolder(PackOutput.Target.DATA_PACK);
    }

    @Override
    public CompletableFuture<?> run(CachedOutput output) {
        List<CompletableFuture<?>> futures = new ArrayList<>();
        Set<ResourceLocation> written = new HashSet<>();

        for (PlantMaterial material : PlantMaterials.ALL) {
            if (!PlantMaterialGenerator.hasProcessSource(material)) continue;
            ResourceLocation biomass = PlantProcessingPlanner.intermediateId(
                    material,
                    PlantProcessingPlanner.BIOMASS
            );

            for (var entry : material.existingParts().entrySet()) {
                PlantPart part = entry.getKey();
                if (!part.biomassSource()) continue;

                ResourceLocation input = entry.getValue();
                if (input.getNamespace().equals("minecraft") || input.getNamespace().equals("create")) {
                    continue;
                }

                String createType = PlantProcessingPlanner.usesGrindingPreparation(part)
                        ? "milling"
                        : "cutting";
                ResourceLocation recipeId = recipeId(material, part, createType);
                saveProcessing(
                        futures,
                        output,
                        written,
                        recipeId,
                        createType,
                        input,
                        biomass,
                        1,
                        PlantProcessingPlanner.createPreparationTicks(material, part)
                );
            }
        }

        saveProcessing(futures,output,written,
                ResourceLocation.fromNamespaceAndPath("industron","recipes/food/milling/grain_to_flour"),
                "milling",ResourceLocation.parse("industron:wheat_grain"),ResourceLocation.parse("industron:wheat_flour"),1,net.mads.industron.integration.create.kinetic.KineticProcessingRules.referenceDuration(50));
        return CompletableFuture.allOf(futures.toArray(CompletableFuture[]::new));
    }

    private static ResourceLocation recipeId(
            PlantMaterial material,
            PlantPart part,
            String createType
    ) {
        return ResourceLocation.fromNamespaceAndPath(
                Industron.MOD_ID,
                "plant_processing/" + createType + "/" + material.id() + "/" + part.name().toLowerCase()
        );
    }

    private void saveProcessing(
            List<CompletableFuture<?>> futures,
            CachedOutput output,
            Set<ResourceLocation> written,
            ResourceLocation recipeId,
            String createType,
            ResourceLocation input,
            ResourceLocation result,
            int resultCount,
            int processingTime
    ) {
        if (!written.add(recipeId)) {
            throw new IllegalStateException("Duplicate generated Create plant recipe id: " + recipeId);
        }

        JsonObject recipe = new JsonObject();
        recipe.addProperty("type", "create:" + createType);

        JsonArray ingredients = new JsonArray();
        JsonObject ingredient = new JsonObject();
        ingredient.addProperty("item", input.toString());
        ingredients.add(ingredient);
        recipe.add("ingredients", ingredients);
        recipe.addProperty("processing_time", processingTime);

        JsonArray results = new JsonArray();
        JsonObject outputItem = new JsonObject();
        outputItem.addProperty("id", result.toString());
        if (resultCount != 1) outputItem.addProperty("count", resultCount);
        results.add(outputItem);
        recipe.add("results", results);

        Path path = dataPackRoot.resolve(recipeId.getNamespace())
                .resolve("recipe")
                .resolve(recipeId.getPath() + ".json");
        futures.add(DataProvider.saveStable(output, recipe, path));
    }

    @Override
    public String getName() {
        return "Create Plant Processing Recipes: " + Industron.MOD_ID;
    }
}
