package net.mads.industron.data;

import net.mads.industron.Industron;
import net.mads.industron.material.structure.StructureMaterial;
import net.mads.industron.material.structure.StructureMaterialGenerator;
import net.mads.industron.material.MaterialPart;
import net.mads.industron.material.structure.StructureMaterialVariantResolver;
import net.mads.industron.material.structure.StructureMaterials;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.neoforge.client.model.generators.ItemModelProvider;
import net.neoforged.neoforge.client.model.generators.ModelFile;
import net.neoforged.neoforge.client.model.generators.ModelProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;

/** Generates item models for structure-material dust and wood-pulp forms. */
public final class StructureMaterialItemModelProvider extends ItemModelProvider {
    private final ExistingFileHelper existingFileHelper;

    public StructureMaterialItemModelProvider(PackOutput output, ExistingFileHelper existingFileHelper) {
        super(output, Industron.MOD_ID, existingFileHelper);
        this.existingFileHelper = existingFileHelper;
    }

    @Override
    public String getName() {
        return "Structure Material Item Models: " + Industron.MOD_ID;
    }

    @Override
    protected void registerModels() {
        for (StructureMaterial material : StructureMaterials.ALL) {
            for (MaterialPart part : StructureMaterialGenerator.generatedItemForms(material)) {
                // Pebbles deliberately have no item texture of their own. Like slabs/walls/stairs,
                // their appearance comes from model geometry + the material's STONE texture.
                // Reuse the loose-pebble block model so held/inventory Pebbles and worldgen Pebbles
                // are the same physical form and can never drift apart visually.
                if (material instanceof net.mads.industron.material.structure.StoneMaterial stone
                        && part == MaterialPart.PEBBLE) {
                    getBuilder(part.registryName(material)).parent(new ModelFile.UncheckedModelFile(
                            ResourceLocation.fromNamespaceAndPath(
                                    Industron.MOD_ID,
                                    "block/loose_pebble/" + stone.id()
                            )
                    ));
                    continue;
                }

                if (material instanceof net.mads.industron.material.structure.WoodMaterial wood
                        && part == MaterialPart.STICK) {
                    existingFileHelper.trackGenerated(
                            StructureMaterialVariantResolver.generatedWoodStickTexture(wood),
                            ModelProvider.TEXTURE
                    );
                }
                if (material instanceof net.mads.industron.material.structure.WoodMaterial wood
                        && part == MaterialPart.BARK
                        && !wood.hasExistingPart(MaterialPart.LOG)) {
                    existingFileHelper.trackGenerated(
                            net.mads.industron.material.structure.StructureSetResolver.generatedTexture(
                                    wood,
                                    wood.model().id() + "_planks.png"
                            ),
                            ModelProvider.TEXTURE
                    );
                }
                if (material instanceof net.mads.industron.material.structure.WoodMaterial wood) {
                    StructureMaterialVariantResolver.woodUtilityTextureFile(part).ifPresent(file ->
                            existingFileHelper.trackGenerated(
                                    net.mads.industron.material.structure.StructureSetResolver.generatedTexture(wood, file),
                                    ModelProvider.TEXTURE
                            )
                    );
                }

                // Stone tool-head textures are generated by StructureMaterialTextureProvider in the
                // same datagen run. ExistingFileHelper does not automatically index arbitrary files
                // produced by another provider, so mark these known generated textures before
                // ModelBuilder validates the layer reference. This mirrors the existing structure
                // block-state provider's handling of generated structure textures.
                if (material instanceof net.mads.industron.material.structure.StoneMaterial stone
                        && StructureMaterialVariantResolver.isStoneShapingPart(part)) {
                    existingFileHelper.trackGenerated(
                            StructureMaterialVariantResolver.generatedStoneToolTexture(stone, part),
                            ModelProvider.TEXTURE
                    );
                }

                StructureMaterialVariantResolver.itemTextures(material, part).ifPresent(textures -> {
                    var model = getBuilder(part.registryName(material))
                            .parent(new ModelFile.UncheckedModelFile(ResourceLocation.withDefaultNamespace("item/generated")))
                            .texture("layer0", textures.base());
                    textures.secondary().ifPresent(texture -> model.texture("layer1", texture));
                    textures.overlay().ifPresent(texture -> model.texture("layer2", texture));
                    ToolPartModelAlignment.apply(model, part);
                });
            }
        }
    }
}
